[model]
img_width = 128
img_height = 128
model_architecture = "CNN_FaceRecognition_v1"
augmentation_used = true
num_classes = 2

[data]
data_path = "../../../dados/fotos_train"
timestamp = "2025-11-02T20:47:47.908"
person_names = ["junior", "lele"]

[metadata]
created_by = "CNNCheckin v2.0"
version = "2.0"
description = "Sistema de reconhecimento facial com aprendizado incremental"
last_saved = "2025-11-02T20:47:48.085"

[training]
epochs = 30
best_epoch = 2
batch_size = 8
learning_rate = 0.0001
final_accuracy = 1.0
epochs_trained = 2
