prediction_examples = []

[[layer_info]]
trainable = true
output_channels = 64
layer_number = 1
kernel_size = [3, 3]
input_channels = 3
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 2
num_features = 64
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 3
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 4
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 128
layer_number = 5
kernel_size = [3, 3]
input_channels = 64
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 6
num_features = 128
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 7
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 8
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 9
kernel_size = [3, 3]
input_channels = 128
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 10
num_features = 256
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 11
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 12
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 13
kernel_size = [3, 3]
input_channels = 256
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 14
num_features = 256
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 15
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 16
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
layer_number = 17
layer_type = "typeof(Flux.flatten)"
[[layer_info]]
trainable = true
layer_number = 18
input_size = 16384
output_size = 512
layer_type = "Flux.Dense{typeof(NNlib.relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 19
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 20
input_size = 512
output_size = 256
layer_type = "Flux.Dense{typeof(NNlib.relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 21
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 22
input_size = 256
output_size = 3
layer_type = "Flux.Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}"

[person_mappings]
junior = 1
cachorro = 3
lele = 2

[model_summary]
input_shape = [128, 128]
created_at = "2025-11-06T15:23:51.055"
total_layers = 22
model_type = "CNN_FaceRecognition"
output_classes = 3

[metadata]
format_version = "2.0"
created_by = "CNNCheckin v2.0"
saved_at = "2025-11-06T15:23:51.623"
description = "Metadados do modelo CNN para reconhecimento facial"

[weights_summary]
model_size_mb = 36.17
total_parameters = 9480640

    [weights_summary.layer_statistics.layer_20_weights]
    shape = [256, 512]
    max = 0.08916275203227997
    min = -0.08920864015817642
    count = 131072
    mean = 5.6928452977444977e-5
    std = 0.051025860011577606

    [weights_summary.layer_statistics.layer_22_weights]
    shape = [3, 256]
    max = 0.15222251415252686
    min = -0.15147975087165833
    count = 768
    mean = -0.00014214492694009095
    std = 0.07299556583166122

    [weights_summary.layer_statistics.layer_5_weights]
    shape = [3, 3, 64, 128]
    max = 0.059997864067554474
    min = -0.059999026358127594
    count = 73728
    mean = -0.00034388958010822535
    std = 0.03397240489721298

    [weights_summary.layer_statistics.layer_1_weights]
    shape = [3, 3, 3, 64]
    max = 0.09988010674715042
    min = -0.09984593838453293
    count = 1728
    mean = 0.0015434565721079707
    std = 0.05701605975627899

    [weights_summary.layer_statistics.layer_13_weights]
    shape = [3, 3, 256, 256]
    max = 0.037366073578596115
    min = -0.03740004822611809
    count = 589824
    mean = -3.136596569675021e-5
    std = 0.020820772275328636

    [weights_summary.layer_statistics.layer_18_weights]
    shape = [512, 16384]
    max = 0.02031586319208145
    min = -0.02025148831307888
    count = 8388608
    mean = -0.00010598498192848638
    std = 0.010891218669712543

    [weights_summary.layer_statistics.layer_9_weights]
    shape = [3, 3, 128, 256]
    max = 0.042781610041856766
    min = -0.042876169085502625
    count = 294912
    mean = 2.3800432700227248e-6
    std = 0.024079781025648117
