prediction_examples = []

[[layer_info]]
trainable = true
output_channels = 64
layer_number = 1
kernel_size = [3, 3]
input_channels = 3
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 2
num_features = 64
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 3
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 4
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 128
layer_number = 5
kernel_size = [3, 3]
input_channels = 64
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 6
num_features = 128
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 7
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 8
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 9
kernel_size = [3, 3]
input_channels = 128
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 10
num_features = 256
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 11
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 12
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 13
kernel_size = [3, 3]
input_channels = 256
layer_type = "Flux.Conv{2, 4, typeof(NNlib.relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 14
num_features = 256
layer_type = "Flux.BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 15
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 16
pool_size = [2, 2]
layer_type = "Flux.MaxPool{2, 4}"
[[layer_info]]
trainable = true
layer_number = 17
layer_type = "typeof(Flux.flatten)"
[[layer_info]]
trainable = true
layer_number = 18
input_size = 16384
output_size = 512
layer_type = "Flux.Dense{typeof(NNlib.relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 19
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 20
input_size = 512
output_size = 256
layer_type = "Flux.Dense{typeof(NNlib.relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 21
layer_type = "Flux.Dropout{Float64, Colon, Random.TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 22
input_size = 256
output_size = 2
layer_type = "Flux.Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}"

[person_mappings]
junior = 1
lele = 2

[model_summary]
input_shape = [128, 128]
created_at = "2025-11-03T16:20:07.385"
total_layers = 22
model_type = "CNN_FaceRecognition"
output_classes = 2

[metadata]
format_version = "2.0"
created_by = "CNNCheckin v2.0"
saved_at = "2025-11-03T16:20:07.959"
description = "Metadados do modelo CNN para reconhecimento facial"

[weights_summary]
model_size_mb = 36.16
total_parameters = 9480384

    [weights_summary.layer_statistics.layer_20_weights]
    shape = [256, 512]
    max = 0.08928216248750687
    min = -0.08921431005001068
    count = 131072
    mean = -6.567544915014878e-5
    std = 0.0509776771068573

    [weights_summary.layer_statistics.layer_22_weights]
    shape = [2, 256]
    max = 0.15173999965190887
    min = -0.15147322416305542
    count = 512
    mean = -0.004492373205721378
    std = 0.09193992614746094

    [weights_summary.layer_statistics.layer_5_weights]
    shape = [3, 3, 64, 128]
    max = 0.060123998671770096
    min = -0.06008050590753555
    count = 73728
    mean = -0.0001482886291341856
    std = 0.03403600677847862

    [weights_summary.layer_statistics.layer_1_weights]
    shape = [3, 3, 3, 64]
    max = 0.09991361945867538
    min = -0.10073178261518478
    count = 1728
    mean = -0.00014635082334280014
    std = 0.05711682140827179

    [weights_summary.layer_statistics.layer_13_weights]
    shape = [3, 3, 256, 256]
    max = 0.03732511028647423
    min = -0.037367090582847595
    count = 589824
    mean = 3.195218232576735e-5
    std = 0.020862478762865067

    [weights_summary.layer_statistics.layer_18_weights]
    shape = [512, 16384]
    max = 0.02028622105717659
    min = -0.0202226173132658
    count = 8388608
    mean = -9.559746104059741e-5
    std = 0.010892060585319996

    [weights_summary.layer_statistics.layer_9_weights]
    shape = [3, 3, 128, 256]
    max = 0.04281717911362648
    min = -0.04283703863620758
    count = 294912
    mean = 6.577262684004381e-5
    std = 0.02404876984655857
